name: Java CI with Gradle
 
on:
  #schedule: 
    #- cron: * * * * *
   
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
permissions:
  contents: read
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        
    - name: Artifact    
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: src/
        if-no-files-found: error
        retention-days: 90

    - name: Set up Docker Buildx and push
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker Image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "vijayakumar626" --password-stdin
        docker image build -t dockerimage:1.1.0 .
        dokcer push dockerimage:1.1.0
         
